/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.duncte123.colorutils;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
